spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: nld_admin
    password: Nld123456789%
    url: jdbc:mysql://rm-uf6a4u8iozaa9o637o.mysql.rds.aliyuncs.com:3306?useSSL=false&amp;characterEncoding=utf8&amp;characterSetResults=utf8
server:
  port: 8580
  servlet:
    context-path: /addedValue/